<Project>
	<PropertyGroup>
		<MinimumRequiredDmVersion>10.6.3.0 - 16832</MinimumRequiredDmVersion>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="..\.editorconfig">
			<Link>Properties\.editorconfig</Link>
		</Content>
		<AdditionalFiles Include="..\allowed_words.dic">
			<Link>Properties\allowed_words.dic</Link>
		</AdditionalFiles>
	</ItemGroup>
</Project>